### PR TITLE
Adds additional validation to object info set identifier value and resolves #428 bug

### LINKED ISSUE #428: Convention mapping when entity is generic type includes grave accent (backtick) character
Consider

``` c#
public class Customer {}
public class Customer<int> {}
```

Either, in my opinion, should resolve to a table name of `Customer`. However, currently the generic type version resolves to ``Customer`1``.

### PR DESCRIPTION
**Pull request by pleb**
Brings ObjectInfo.SetIdentifier inline with ObjectInfo.GetIndentifier

### CODE REVIEW

**Comment by pleb** [comment]
I thought "yeah you're right" and opps. But, when I went to remove it I found there maybe was a little confusion between the `VerifyInstanceIsCorrectTypeForThisObjectInfo` doing an `instance` check, and the null check I added for `identifier`. Thoughts?

**Comment by pleb** [comment]
Agree. I'll update PR

**Comment by pleb** [comment]
PR Updated

**Comment by pleb** [comment]
@TrevorPilley  please be aware this PR now includes a fix for bug #428. I wasn't sure of the best way to split these.

**Comment by TrevorPilley** [comment]
@pleb OK, I'll review this tomorrow (1st Dec) and look at publishing 6.2.7 with these changes in.

**Comment by pleb** [comment]
@TrevorPilley regarding #428 I noticed a few places where Type.Name is used while implementing optimistic concurrency. None of these places are critical, more for exception messages. Maybe worth a ticket to standardise getting the name - possible Type extension method. Thoughts?

**Comment by TrevorPilley** [comment]
Give me an example of what you mean?

**Comment by pleb** [comment]
Sorry mate, I got it wrong please disregard comment. Confusion between Type.Name and Type.FullName usage.

**Pull request merged**
