### PR TITLE
Adds support for table row versioning (Optimistic concurrency control) #427

### PR DESCRIPTION
**Pull request by pleb**
Updates mapping attribute class diagram

Adds entity version is updated when update is successful

Adds throw DBConcurrencyException if a versioned updated fails

Removes param instance null checked in object info set identifier value

  - Removes a null check, as per PR review

Removes param instance null checked in object info set version value

  - Brings method inline with set identity

Reverts all tests to state prior to version changes

  - Reverts all tests to state prior to version changes, as per
    code review.

Fixes incorrect table name when entity is generic type

Adds unit tests to version feature (Optimistic concurrency control)

  - Adds unit tests, as initial tests were revert due to code review
    feedback

Fixes formatting bug in Session_UpdateOptimisticConcurrencyError message

Adds delete support to table row versioning (Optimistic concurrency)

Adds DeleteAsync by type, identifier, and version API

  - Adds DeleteAsync by type, identifier, and version API which is useful
    when wanting to delete entities without loading them first. (Web)

  - Includes minor bug fixes

  - Includes additional unit tests and logic checks

Fixes incorrect usage of Type.Name and Type.FullName

Fixes bug where return entity's version wasn't updated

Fixes compiler warnings

Updates versioned method to not throw when no records are affected
  - Code reviewer stated method behaviour should not change when
    compared with existing non-versioned ones

### CODE REVIEW

**Comment by pleb** [comment]
@TrevorPilley there you go. one commit :smile:

**Comment by pleb** [comment]
Trevor isn't following up on this, so I'm closing it.

**Comment by TrevorPilley** [comment]
@pleb - this isn't something I want to introduce before MicroLite 7 which is what is coming next but since I have quite a few internal changes to make I don't want to pull in something just before that which is going to be difficult to migrate forward.

In future, I would suggest opening an issue and having the discussion before you start sending pull requests through to make sure that it's something in line with the project roadmap before you invest the effort on your own part.

**Comment by pleb** [comment]
In future don't keep requesting additional change in the PR, if you're not interested accepting it.

**Comment by TrevorPilley** [comment]
@pleb - I wanted it in a state where I could actually see what changes you were proposing which your original PR didn't easily allow

**Pull request closed without merging**
